# Generated by Django 3.2.4 on 2021-10-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('fno', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.TextField(default='')),
                ('Disc', models.TextField(default='')),
                ('Admin_Name', models.CharField(max_length=550)),
                ('Admin_Email', models.CharField(max_length=550)),
                ('Admin_Username', models.CharField(default='', max_length=1000)),
                ('Timestamp_Created', models.CharField(max_length=505)),
                ('Extras', models.TextField(default='')),
            ],
        ),
    ]
